### ISSUE TITLE
Unsupported Media Type

### ISSUE THREAD

**Issue by luis360** [transistive/neo4j-php-client#3]
Unsupported Media Type

  at vendor/php-http/client-common/src/Plugin/ErrorPlugin.php:72

version: 4.1.3

**Comment by transistive** [comment]
Dear luls360, 
I updated the neo4j version and ran all the tests. No issues found. Would you please provide more details? 
Kind regards,
Ghlen

**Comment by letordj** [comment]
HI @luis360,

I think your error is due to php requirement version  7.4,
if your php version is a lower than php 7.4 previous version of neo4j-php-client will be installed.

@transistive is it possible to made small fixes to make the package compatible with php 7 ?
It would be more flexible for all install types.

Have a nice day.

**Comment by transistive** [comment]
Dear @letordj 
I am not sure the error of @luis360 is because of the php version, as that would most likely introduce a parsing error instead of a runtime one.

Regarding the php versions: I see php 7.2 will only receive security updates until the 30th of November:
![image](https://user-images.githubusercontent.com/16435930/96440320-1964b200-1208-11eb-9ac8-d051c6df0922.png)

Because of this reason, I will only be able to lower the php requirement to 7.3. Feel free to open a new issue, and I will fix it this week.

Kind regards,
Ghlen

**Comment by letordj** [comment]
Hi @transistive, 
Php 7.3 will be allright. Thanks a lot !

**Comment by transistive** [comment]
Sorry for the delay, it is fixed now!
